package com.opendevsolutions._23seguro;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Student implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private int qualification;

	private int worksDelivered;

	private java.lang.String status;

	public Student() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getQualification() {
		return this.qualification;
	}

	public void setQualification(int qualification) {
		this.qualification = qualification;
	}

	public int getWorksDelivered() {
		return this.worksDelivered;
	}

	public void setWorksDelivered(int worksDelivered) {
		this.worksDelivered = worksDelivered;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Student(java.lang.String name, int qualification,
			int worksDelivered, java.lang.String status) {
		this.name = name;
		this.qualification = qualification;
		this.worksDelivered = worksDelivered;
		this.status = status;
	}

}